version: "3.8"
services:
  db:
    container_name: commsenso
    tty: true
    image: postgres:17.0
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=commsensodb
    ports:
      - "5432:5432"
