services:
  rest_api:
    container_name: commsenso_api
    build:
      context: .
      dockerfile: Dockerfile
    image: commsenso_api:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "npx sequelize-cli db:migrate && node dist/server.js"
  db:
    container_name: commsenso_db
    tty: true
    image: postgres:17.0
    volumes:
      - rest_commsenso_dbdata:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  rest_commsenso_dbdata:
